services:
  backend:
    build:
      context: ./Proyecto_TiendaNC
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    ports:
      - "8080:8080"
    container_name: backend
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=tiendanc
      - MINIO_PUBLIC_URL=https://minio.laleyendadeldulce.com
    depends_on:
      - database 
      - minio
    networks:
      - tienda-red

  frontend:
    build:
      context: ./Proyecto_Tienda_frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    container_name: frontend
    environment:
      - TZ=America/Mexico_City
    depends_on:
      - backend
    networks:
      - tienda-red

  database: 
    image: postgres:13
    environment:
      POSTGRES_DB: dulcesnc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: America/Mexico_City
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    container_name: Dulceria-DB
    ports:
      - "5432:5432" 
    networks:
      - tienda-red

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - tienda-red

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command: >
      tunnel run 
      --token eyJhIjoiNzhmZTUxOGI2OGVlODZjZmJjYjdjMTI2NzY1N2Q2MmIiLCJ0IjoiNWYzNGQwNjYtZDE4NC00NzhhLTk4ZDItYjliMzJkY2M3ZDljIiwicyI6Ik1tWmpOV0kwWXpZdFpHRXpNeTAwTkRBeExXSTNaVFl0WVRCbU9ETTNZbVk1TXpWaSJ9
    environment:
      - TUNNEL_ORIGIN_SERVER_NAME=api.laleyendadeldulce.com
      - NO_TLS_VERIFY=true
      - TUNNEL_METRICS=0.0.0.0:9090
      - TUNNEL_LOGLEVEL=info
    networks:
      - tienda-red
    depends_on:
      - frontend
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  tienda-red:
    driver: bridge

volumes:
  db-data:
  minio-data: